config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'events#index'

  get '/welcome' => 'application#welcome', as: :application_welcome

  get '/events/add' => 'events#add', as: :events_add
  post '/events/add' => 'events#add', as: :events_add_post
  get '/events(/:event_time)' => 'events#index', as: :events_index

  get '/hosts/register' => 'hosts#register', as: :hosts_register
  post '/hosts/register' => 'hosts#register', as: :hosts_register_post
  get '/hosts/login' => 'hosts#login', as: :hosts_login
  post '/hosts/login' => 'hosts#login', as: :hosts_login_post
  get '/hosts/edit_profile' => 'hosts#edit_profile', as: :hosts_edit_profile
  post '/hosts/edit_profile' => 'hosts#edit_profile', as: :hosts_edit_profile_post
  get '/hosts/logout' => 'hosts#logout', as: :hosts_logout

  get '/users/register' => 'users#register', as: :users_register
  post '/users/register' => 'users#register', as: :users_register_post
  get '/users/login' => 'users#login', as: :users_login
  post '/users/login' => 'users#login', as: :users_login_post
  get '/users/edit_profile' => 'users#edit_profile', as: :users_edit_profile
  post '/users/edit_profile' => 'users#edit_profile', as: :users_edit_profile_post
  get '/users/logout' => 'users#logout', as: :users_logout

  get '/rsvps' => 'rsvps#index', as: :rsvps_index
  get '/rsvps/:event_id' => 'rsvps#export', as: :rsvps_export
  get '/rsvps/add/:event_id' => 'rsvps#add', as: :rsvps_add
  post '/rsvps/add/:event_id/:user_id' => 'rsvps#add', as: :rsvps_add_post
  get '/rsvps/confirm/:event_id' => 'rsvps#confirm', as: :rsvps_confirm
  post '/rsvps/confirm/:event_id' => 'rsvps#confirm', as: :rsvps_confirm_post

end

app/models/user.rb
class User < ApplicationRecord

  has_many :rsvps
  has_many :events, through: :rsvps

  attr_accessor :registration_password, :registration_password_repeat

  validates :email_addr, :passwd, :first_name, :last_name, :phone, presence: true
  validates :email_addr, uniqueness: true

  def evaluate_registration
    if registration_password != registration_password_repeat
      errors.add(:registration_password, "and confirmation password don't match")
    elsif registration_password.blank?
      errors.add(:registration_password, 'required')
    end
    
    self.passwd = Digest::SHA256.hexdigest registration_password
  end

  def self.search_by_name(search)
    where("first_name LIKE ? OR last_name LIKE ?", "%#{search}%", "%#{search}%") 
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :authorize, :only => [:register, :login]
  
  def register
    if request.post?
      @user = User.new(user_params)
      @user.evaluate_registration
      if @user.valid? && @user.save
        session[:account_type] = 'user'
        session[:user_id] = @user.id
        redirect_to events_index_path
      else
        flash[:error] = @user.errors.full_messages.map { |v| v }.join('<br/>')
        redirect_to users_register_path
      end
    else
      @user = User.new
    end
  end

  def login
    if request.post?
      user = User.find_by(email_addr: params[:email_addr], passwd: Digest::SHA256.hexdigest(params[:passwd]))
      if !user.blank?
        session[:account_type] = 'user'
        session[:user_id] = user.id
        redirect_to events_index_path
      else
        redirect_to users_login_path
      end
    end
  end

  def logout
    session[:account_type] = nil
    session[:user_id] = nil
    session[:host_id] = nil
    redirect_to application_welcome_path
  end

  def edit_profile
    if request.post?
      if @current_user.update(user_params)
        flash[:success] = 'Profile Updated'
        redirect_to users_edit_profile_path
      else
        flash[:error] = @current_user.errors.full_messages.map { |v| v }.join('<br/>')
        redirect_to users_edit_profile_path
      end
    else
      @user = @current_user
    end
  end

  private

  def user_params
    params.require(:user).permit(:email_addr, :registration_password, :registration_password_repeat, :first_name, :last_name, :phone, :addr1, :addr2, :city, :state, :zip)
  end

end

app/views/users/edit_profile.html.erb
<div class="users form">
    <%= form_for @user, url: users_edit_profile_path, method: :post do |f| %>
        <fieldset>
            <legend>User Registration</legend>
            <%= f.label "email_addr", "Email Address *" %>
            <%= f.text_field "email_addr" %>
            <%= f.label "first_name", "First Name *" %>
            <%= f.text_field "first_name" %>
            <%= f.label "last_name", "Last Name *" %>
            <%= f.text_field "last_name" %>
            <%= f.label "phone", "Phone Number *" %>
            <%= f.text_field "phone" %>
            <%= f.label "addr1", "Address 1" %>
            <%= f.text_field "addr1" %>
            <%= f.label "addr2", "Address 2" %>
            <%= f.text_field "addr2" %>
            <%= f.label "city", "City" %>
            <%= f.text_field "city" %>
            <%= f.label "state", "State" %>
            <%= f.text_field "state" %>
            <%= f.label "zip", "Zip" %>
            <%= f.text_field "zip" %>
        </fieldset>
        <div style="float:right;">
            <%= f.submit "Update" %>
        </div>
        <div style="clear:both;"></div>
    <% end %>
</div>

app/views/users/login.html.erb
<div class="loginForm">
    <h2>User Log In</h2>
    <%= form_tag users_login_path, method: :post do %>
      <%= label_tag "email_addr", "Email Address" %>
      <%= text_field_tag "email_addr" %>
      <%= label_tag "passwd", "Password" %>
      <%= password_field_tag "passwd" %>
      <%= submit_tag "Login" %>
    <% end %>
</div>
<br/>
<div class="loginForm">
    <p>Don't have a socialite account?</p>
    <br/>
    <%= link_to "Register Now", users_register_path %>
    <br/>
    <%= link_to "Login as a host", hosts_login_path %>
</div>

app/views/users/register.html.erb
<div class="loginForm">
    <%= form_for @user, url: users_register_path, method: :post do |f| %>
        <fieldset>
            <legend>User Registration</legend>
            <%= f.label "email_addr", "Email Address *" %>
            <%= f.text_field "email_addr" %>
            <%= f.label "registration_password", "Password *" %>
            <%= f.password_field "registration_password" %>
            <%= f.label "registration_password_repeat", "Repeat Password *" %>
            <%= f.password_field "registration_password_repeat" %>
            <%= f.label "first_name", "First Name *" %>
            <%= f.text_field "first_name" %>
            <%= f.label "last_name", "Last Name *" %>
            <%= f.text_field "last_name" %>
            <%= f.label "phone", "Phone Number *" %>
            <%= f.text_field "phone" %>
        </fieldset>
        <div style="float:right;">
            <%= f.submit "Register" %>
        </div>
        <div style="clear:both;"></div>
    <% end %>
</div>