config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'events#index'

  get '/welcome' => 'application#welcome', as: :application_welcome

  get '/events/add' => 'events#add', as: :events_add
  post '/events/add' => 'events#add', as: :events_add_post
  get '/events(/:event_time)' => 'events#index', as: :events_index

  get '/hosts/register' => 'hosts#register', as: :hosts_register
  post '/hosts/register' => 'hosts#register', as: :hosts_register_post
  get '/hosts/login' => 'hosts#login', as: :hosts_login
  post '/hosts/login' => 'hosts#login', as: :hosts_login_post
  get '/hosts/edit_profile' => 'hosts#edit_profile', as: :hosts_edit_profile
  post '/hosts/edit_profile' => 'hosts#edit_profile', as: :hosts_edit_profile_post
  get '/hosts/logout' => 'hosts#logout', as: :hosts_logout

  get '/users/register' => 'users#register', as: :users_register
  post '/users/register' => 'users#register', as: :users_register_post
  get '/users/login' => 'users#login', as: :users_login
  post '/users/login' => 'users#login', as: :users_login_post
  get '/users/edit_profile' => 'users#edit_profile', as: :users_edit_profile
  post '/users/edit_profile' => 'users#edit_profile', as: :users_edit_profile_post
  get '/users/logout' => 'users#logout', as: :users_logout

  get '/rsvps' => 'rsvps#index', as: :rsvps_index
  get '/rsvps/:event_id' => 'rsvps#export', as: :rsvps_export
  get '/rsvps/add/:event_id' => 'rsvps#add', as: :rsvps_add
  post '/rsvps/add/:event_id/:user_id' => 'rsvps#add', as: :rsvps_add_post
  get '/rsvps/confirm/:event_id' => 'rsvps#confirm', as: :rsvps_confirm
  post '/rsvps/confirm/:event_id' => 'rsvps#confirm', as: :rsvps_confirm_post

end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :host

  has_many :rsvps
  has_many :users, through: :rsvps

  enum event_type: [:public, :invite], _prefix: true

  validates :event_name, :capacity, :event_start, :event_end, :rsvp_start, :rsvp_end, :event_type, :venue_addr1, :venue_city, :venue_state, :venue_zip, presence: true

  def self.get_upcoming_public_events
    self.where(event_type: :public).where('`event_start` >= ?', Time.now)
  end

  def self.get_past_public_events
    self.where(event_type: :public).where('`event_start` < ?', Time.now)
  end

  def self.get_upcoming_events_by_host(host_id)
    self.where(host_id: host_id).where('`event_start` >= ?', Time.now)
  end

  def self.get_past_events_by_host(host_id)
    self.where(host_id: host_id).where('`event_start` < ?', Time.now)
  end

  def self.get_upcoming_invite_events_for_user(user_id)
    self.joins(:rsvps).where(event_type: :invite).where(rsvps: {user_id: user_id}).where('`event_start` >= ?', Time.now)
  end

  def self.get_past_invite_events_for_user(user_id)
    self.joins(:rsvps).where(event_type: :invite).where(rsvps: {user_id: user_id}).where('`event_start` < ?', Time.now)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :only_host_action, :only => [:add]

  def index
    @event_time = if params[:event_time].blank? || ['upcoming', 'past'].index(params[:event_time]).nil?
      'upcoming'
    else
      params[:event_time]
    end

    @events = if @account_type == 'host'
      if @event_time == 'upcoming'
        Event.get_upcoming_events_by_host(@current_host.id)
      else
        Event.get_past_events_by_host(@current_host.id)
      end
    else
      if @event_time == 'upcoming'
        #Add invite events to public events for users and sort by start date
        (Event.get_upcoming_public_events + Event.get_upcoming_invite_events_for_user(@current_user.id)).sort_by {|event| event.event_start}
      else
        (Event.get_past_public_events + Event.get_past_invite_events_for_user(@current_user.id)).sort_by {|event| event.event_start}
      end
    end
  end

  def add
    if request.post?
      @event = Event.new(event_params.merge(host_id: @current_host.id))
      if @event.valid? && @event.save
        redirect_to events_index_path
      else
        flash[:error] = @event.errors.full_messages.map { |v| v }.join('<br/>')
        redirect_to events_add_path
      end
    else
      @event = Event.new
    end
  end

  private

  def event_params
    params.require(:event).permit(:event_name, :description, :capacity, :event_start, :event_end, :rsvp_start, :rsvp_end, :event_type, :venue_addr1, :venue_addr2, :venue_city, :venue_state, :venue_zip)
  end

end

app/views/events/add.html.erb
<div class="events form">
    <%= form_for @event, url: events_add_path, method: :post do |f| %>
        <fieldset>
            <legend>Add Event</legend>
            <%= f.label "event_name", "Event Name *" %>
            <%= f.text_field "event_name" %>
            <%= f.label "description", "Description" %>
            <%= f.text_area "description" %>
            <%= f.label "capacity", "Capacity *" %>
            <%= f.text_field "capacity" %>
            <%= f.label "event_start", "Event Start *" %>
            <%= f.datetime_field "event_start" %>
            <%= f.label "event_end", "Event End *" %>
            <%= f.datetime_field "event_end" %>
            <%= f.label "rsvp_start", "RSVP Start *" %>
            <%= f.datetime_field "rsvp_start" %>
            <%= f.label "rsvp_end", "RSVP End *" %>
            <%= f.datetime_field "rsvp_end" %>
            <%= f.label "event_type", "Event Type *" %>
            <%= f.select "event_type", options_for_select(Event.event_types.inject({}){ |het, et| het.merge( et.first.capitalize => et.first )}), { style: 'width: 100%;' } %>
            <%= f.label "venue_addr1", "Venue Address 1 *" %>
            <%= f.text_field "venue_addr1" %>
            <%= f.label "venue_addr2", "Venue Address 2" %>
            <%= f.text_field "venue_addr2" %>
            <%= f.label "venue_city", "Venue City *" %>
            <%= f.text_field "venue_city" %>
            <%= f.label "venue_state", "Venue State *" %>
            <%= f.text_field "venue_state" %>
            <%= f.label "venue_zip", "Venue Zip *" %>
            <%= f.text_field "venue_zip" %>
        </fieldset>
        <div style="float:right;">
            <%= f.submit "Add" %>
        </div>
        <div style="clear:both;"></div>
    <% end %>
</div>

app/views/events/index.html.erb
<div class="events index">
    <% if @event_time == 'upcoming' %>
        <h2><%= @account_type == 'host' ? 'My Upcoming Events' : 'Upcoming Events' %></h2>
    <% else %>
        <h2><%= @account_type == 'host' ? 'My Past Events' : 'Past Events' %></h2>
    <% end %>
    <table>
        <tr>
            <% if @account_type == 'host' %>
                <td class="actions" width="60">
                    <%= link_to "Add Event", events_add_path %>
                </td>
            <% end %>
            <td class="actions">
                <%= link_to "Upcoming", events_index_path('upcoming') %>
                <%= link_to "Past", events_index_path('past') %>
            </td>
        </tr>
    </table>

    <% if !@events.blank? %>
        <% @events.each do |event| %>
            <h3><%= event.event_name %></h3>
            <div class="event_listing">
                <div class="event_listing_left">
                    <%= image_tag "default_event.jpg", width: "90" %>
                </div>
                <div class="event_listing_right">
                    <p><span class="small_title">Location: </span><%= "#{event.venue_addr1}, #{event.venue_city}, #{event.venue_state} #{event.venue_zip}" %></p>
                    <p><span class="small_title">Start Time: </span><%= event.event_start %></p>
                    <p><span class="small_title">End Time: </span><%= event.event_end %></p>
                    <p><span class="small_title">Details: </span><%= event.description %></p>
                    <% if @account_type == 'host' %>
                        <p><span class="small_title">Type: </span><%= event.event_type %></p>
                        <div class="event_listing_actions">
                        <% if event.event_type == 'invite' and @event_time =='upcoming' %>
                            <%= link_to "Invite", rsvps_add_path(event.id) %>
                        <% end %>
                        <%= link_to "Export RSVP List", rsvps_export_path(event.id, :format => "csv") %>
                        </div>
                    <% else %>
                        <div class="event_listing_actions">
                        <% if @event_time =='upcoming' and event.rsvp_start < Time.now and event.rsvp_end > Time.now and calculate_free_capacity_for_event(event) > 0 %>
                            <%= link_to "RSVP", rsvps_confirm_path(event.id) %>
                        <% elsif @event_time =='upcoming' and event.rsvp_start < Time.now and event.rsvp_end > Time.now and calculate_free_capacity_for_event(event) <= 0 %>
                            <p><span class="notification">Event Full</span></p>
                        <% end %>
                        </div>
                    <% end %>
                </div>
                <div style="clear:both;"></div>
            </div>
        <% end %>
    <% else %>
        <% if @event_time == 'upcoming' %>
            <h3>You have no upcoming events in this section</h3>
        <% else %>
            <h3>You have no past events in this section</h3>
        <% end %>
    <% end %>
</div>