config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'events#index'

  get '/welcome' => 'application#welcome', as: :application_welcome

  get '/events/add' => 'events#add', as: :events_add
  post '/events/add' => 'events#add', as: :events_add_post
  get '/events(/:event_time)' => 'events#index', as: :events_index

  get '/hosts/register' => 'hosts#register', as: :hosts_register
  post '/hosts/register' => 'hosts#register', as: :hosts_register_post
  get '/hosts/login' => 'hosts#login', as: :hosts_login
  post '/hosts/login' => 'hosts#login', as: :hosts_login_post
  get '/hosts/edit_profile' => 'hosts#edit_profile', as: :hosts_edit_profile
  post '/hosts/edit_profile' => 'hosts#edit_profile', as: :hosts_edit_profile_post
  get '/hosts/logout' => 'hosts#logout', as: :hosts_logout

  get '/users/register' => 'users#register', as: :users_register
  post '/users/register' => 'users#register', as: :users_register_post
  get '/users/login' => 'users#login', as: :users_login
  post '/users/login' => 'users#login', as: :users_login_post
  get '/users/edit_profile' => 'users#edit_profile', as: :users_edit_profile
  post '/users/edit_profile' => 'users#edit_profile', as: :users_edit_profile_post
  get '/users/logout' => 'users#logout', as: :users_logout

  get '/rsvps' => 'rsvps#index', as: :rsvps_index
  get '/rsvps/:event_id' => 'rsvps#export', as: :rsvps_export
  get '/rsvps/add/:event_id' => 'rsvps#add', as: :rsvps_add
  post '/rsvps/add/:event_id/:user_id' => 'rsvps#add', as: :rsvps_add_post
  get '/rsvps/confirm/:event_id' => 'rsvps#confirm', as: :rsvps_confirm
  post '/rsvps/confirm/:event_id' => 'rsvps#confirm', as: :rsvps_confirm_post

end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
  belongs_to :event
  belongs_to :user

  enum rsvp_status: [:no, :yes], _prefix: true

  validates_uniqueness_of :user_id, scope: :event_id
  validates :guests, numericality: {only_integer: true, greater_than_or_equal_to: 0}

  def self.get_confirmed_rsvps_by_event(event_id)
    self.where(event_id: event_id).where(rsvp_status: 1)
  end

  def self.get_confirmed_rsvps_by_user(user_id)
    self.where(user_id: user_id).where(rsvp_status: 1)
  end

  def self.to_rsvp_list_csv(event_id)
  	rsvps = self.where(event_id: event_id).where.not(rsvp_status: nil).order(rsvp_status: :desc)

  	headers = %w{status first_name last_name email phone_number guests}
  	CSV.generate(headers: true) do |csv|
	  csv << headers

	  rsvps.each do |rsvp|
		  csv << [
		  	rsvp.rsvp_status,
		  	rsvp.user.first_name,
		  	rsvp.user.last_name,
		  	rsvp.user.email_addr,
		  	rsvp.user.phone,
		  	rsvp.guests
		  ]
	  end
  	end
  end

end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController

  helper_method :is_user_invited_to_event
  
  def index
    @rsvps = Rsvp.get_confirmed_rsvps_by_user(current_user.id)
  end

  def add
    @event = Event.find_by(id: params[:event_id])

    if params[:search]
      #clean up whitespace, split on space or comma to allow for multiple names, search on each term
      search = params[:search].strip
      search_terms= search.split(/[\s,]+/)
      search_results = []
      search_terms.each do |term|
        search_results += User.search_by_name(term)
      end
      @users = search_results.uniq
    else
      @users = User.all.limit(50)
    end
    
    if request.post?
      Rsvp.create(event_id: params[:event_id], user_id: params[:user_id])
    end
  end

  def confirm
    #Find existing RSVP, if none exists, create new
    @event = Event.find_by(id: params[:event_id])
    @rsvp = if Rsvp.find_by(event_id: params[:event_id], user_id: @current_user.id).present?
      Rsvp.find_by(event_id: params[:event_id], user_id: @current_user.id)
    else
      Rsvp.new(event_id: params[:event_id], user_id: @current_user.id)
    end

    if request.post?
      #if event is public and rsvp is 'no' then delete rsvp record, else save rsvp after validation
      if @event.event_type == 'public' and rsvp_params["rsvp_status"] == 'no'
        @rsvp.destroy
        redirect_to events_index_path
      else
        if @rsvp.update(rsvp_params)
          redirect_to events_index_path
        else
          flash[:error] = @rsvp.errors.full_messages.map { |v| v }.join('<br/>')
          redirect_to rsvps_confirm_path
        end
      end
    end
  end

  def export    
    respond_to do |format|
      format.html
      format.csv {send_data Rsvp.to_rsvp_list_csv(params[:event_id]), filename: "rsvp-list-#{params[:event_id]}.csv"}
    end
  end

  def is_user_invited_to_event(eventId,userId)
    if Rsvp.find_by(event_id: eventId, user_id: userId).present?
      return true
    else
      return false
    end
  end

  def rsvp_params
    params.require(:rsvp).permit(:rsvp_status, :guests)
  end

end

app/views/rsvps/add.html.erb
<div class="rsvps form">
    <h2>Invite Users to "<%= @event.event_name %>"</h2>

<%= form_tag(rsvps_add_path(@event.id), :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Enter User Name" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

<% if !@users.blank? %>
    <div class="user_search_results">
        <table>
            <tr>
                <th></th>
                <th>First Name</th>
                <th>Last Name</th>
            </tr>
            <% @users.each do |user| %>
                <tr>
                    <% if is_user_invited_to_event(@event.id,user.id) %>
                        <td>Invite Sent</td>
                    <% else %>
                        <td><%= button_to "Invite", rsvps_add_post_path(@event.id, user.id), :method => :post %>
                    <% end %>
                    <td><%= user.first_name %></td>
                    <td><%= user.last_name %></td>
                </tr> 
            <% end %>
        </table>
    </div>
<% end %>

<% if @users.blank? %>
  <h3>There are no users containing the term "<%= params[:search] %>".</h3>
<% end %>

</div>

app/views/rsvps/confirm.html.erb
<div class="rsvps form">
    <%= form_for @rsvp, url: rsvps_confirm_post_path, method: :post do |f| %>
        <fieldset>
            <legend>RSVP to <%= @event.event_name %></legend>
            <%= f.label "rsvp_status", "RSVP? *" %>
            <%= f.select "rsvp_status", options_for_select(Rsvp.rsvp_statuses.inject({}){ |het, et| het.merge( et.first.capitalize => et.first )}, f.object.rsvp_status)%>
            <%= f.label "guests", "Additional Guests *" %>
            <%= f.text_field "guests" %>
            <p><span>Available Capacity: <%= calculate_free_capacity_for_event(@event) %></span></p>
        </fieldset>
        <div style="float:right;">
            <%= f.submit "Submit" %>
        </div>
        <div style="clear:both;"></div>
    <% end %>
</div>

app/views/rsvps/index.html.erb
<div class="events index">
<h2>My Agenda</h2>
<% if !@rsvps.blank? %>
	<table>
	    <tr>
	        <th>Event Start Date</th>
	        <th>Event Name</th>
	        <th>Event Location</th>
	    </tr>
	    <% @rsvps.each do |rsvp| %>
	        <tr>
	            <td><%= rsvp.event.event_start.strftime("%b #{rsvp.event.event_start.day.ordinalize}, %Y %I:%M%P") %></td>
	            <td><%= rsvp.event.event_name %></td>
	            <td><%= "#{rsvp.event.venue_addr1}, #{rsvp.event.venue_city}, #{rsvp.event.venue_state} #{rsvp.event.venue_zip}" %></td>
	        </tr> 
	    <% end %>
	</table>
<% else %>
	<p>You have not RSVP'd to any upcoming events</p>
<% end %>
</div>