config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'events#index'

  get '/welcome' => 'application#welcome', as: :application_welcome

  get '/events/add' => 'events#add', as: :events_add
  post '/events/add' => 'events#add', as: :events_add_post
  get '/events(/:event_time)' => 'events#index', as: :events_index

  get '/hosts/register' => 'hosts#register', as: :hosts_register
  post '/hosts/register' => 'hosts#register', as: :hosts_register_post
  get '/hosts/login' => 'hosts#login', as: :hosts_login
  post '/hosts/login' => 'hosts#login', as: :hosts_login_post
  get '/hosts/edit_profile' => 'hosts#edit_profile', as: :hosts_edit_profile
  post '/hosts/edit_profile' => 'hosts#edit_profile', as: :hosts_edit_profile_post
  get '/hosts/logout' => 'hosts#logout', as: :hosts_logout

  get '/users/register' => 'users#register', as: :users_register
  post '/users/register' => 'users#register', as: :users_register_post
  get '/users/login' => 'users#login', as: :users_login
  post '/users/login' => 'users#login', as: :users_login_post
  get '/users/edit_profile' => 'users#edit_profile', as: :users_edit_profile
  post '/users/edit_profile' => 'users#edit_profile', as: :users_edit_profile_post
  get '/users/logout' => 'users#logout', as: :users_logout

  get '/rsvps' => 'rsvps#index', as: :rsvps_index
  get '/rsvps/:event_id' => 'rsvps#export', as: :rsvps_export
  get '/rsvps/add/:event_id' => 'rsvps#add', as: :rsvps_add
  post '/rsvps/add/:event_id/:user_id' => 'rsvps#add', as: :rsvps_add_post
  get '/rsvps/confirm/:event_id' => 'rsvps#confirm', as: :rsvps_confirm
  post '/rsvps/confirm/:event_id' => 'rsvps#confirm', as: :rsvps_confirm_post

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Socialite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div id="header">
      <div id="logo">
        <%= link_to root_path do %>
          <%= image_tag "logo.png" %>
        <% end %>
      </div>
      <div id="slogan">
        <p></p>
      </div>
      <div id="logout">
        <% if @account_type %>
          <% if @account_type == 'host' %>
            <li><%= link_to "Logout", hosts_logout_path %></li>
          <% else %>
            <li><%= link_to "Logout", users_logout_path %></li>
          <% end %>
        <% end %>
      </div>
    </div>
    <div id="container">
      <div id="content">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value.html_safe %></div>
        <% end %>
        <br/>
        <% if @account_type %>
          <% case @account_type %>
          <% when 'user' %>
            <div id="sidebar-holder">
              <div id="profile">
                <div id="profile_pic">
                  <%= image_tag "default_user.jpg", width: "235" %>
                  <h3 id="profile-name">
                    <%= @current_user.first_name + ' ' + @current_user.last_name %>
                  </h3>
                </div>
              </div>
              <div id="sidebar">
                <h2>Actions</h2>
                <div class="actions">
                  <ul>
                    <li><%= link_to "Events Home", events_index_path %></li>
                    <li><%= link_to "Edit My Profile", users_edit_profile_path %></li>
                    <li><%= link_to "My Agenda", rsvps_index_path %></li>
                  </ul>
                </div>
              </div>
            </div>
          <% when 'host' %>
            <div id="sidebar-holder">
              <div id="profile">
                <div id="profile_pic">
                  <%= image_tag "default_host.jpg", width: "235" %>
                  <h3 id="profile-name">
                    <%= @current_host.business_name %>
                  </h3>
                </div>
              </div>
              <div id="sidebar">
                <h2>Actions</h2>
                <div class="actions">
                  <ul>
                    <li><%= link_to "Events Home", events_index_path %></li>
                    <li><%= link_to "Edit My Profile", hosts_edit_profile_path %></li>
                  </ul>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
        <%= yield %>
      </div>
      <div id="footer">

      </div>
    </div>
  </body>
</html>